function TS30GR1 = importfile30(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TS30GR1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  TS30GR1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  TS30GR1 = importfile("E:\Studium\5,6-Ingenieurgeodaesie\Uebung\IngGeo-6-Semester-Uebung\14\matlab\TS30_GR4.txt", [13, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2020-06-29 23:17:29

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [13, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ID", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "HZ", "V", "SlopeDist", "HorizDist", "dH", "PPM"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "VarName3", "SlopeDist", "HorizDist", "dH", "PPM"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VarName2", "VarName3", "SlopeDist", "HorizDist", "dH", "PPM"], "ThousandsSeparator", ",");

% Import the data
TS30GR1 = readtable(filename, opts);

%% Convert to output type
TS30GR1 = table2array(TS30GR1);
end